#pragma once
// content_tables.h — Struct definitions for RPG binary content files.
// Generated by gen_rpg_packed.py. Do NOT edit manually.
//
// All files use little-endian byte order.
// String pool entries: uint8 length + char[length] (no null terminator in pool).
// 0xFFFF = null/empty string offset.

#include <cstdint>

// ─── Game source bitmask ──────────────────────────────────────────────────
#define GAME_FO1  0x01
#define GAME_FO2  0x02
#define GAME_FO3  0x04
#define GAME_NV   0x08
#define GAME_FO4  0x10

// ─── Faction codes ────────────────────────────────────────────────────────
#define FACTION_CREATURE  0
#define FACTION_GHOUL     1
#define FACTION_RAIDER    2
#define FACTION_MUTANT    3
#define FACTION_ROBOT     4
#define FACTION_HUMAN     5

// ─── Item types ───────────────────────────────────────────────────────────
#define ITYPE_WEAPON      0
#define ITYPE_ARMOR       1
#define ITYPE_CONSUMABLE  2
#define ITYPE_JUNK        3
#define ITYPE_AMMO        4

// ─── Location types ───────────────────────────────────────────────────────
#define LTYPE_VAULT       0
#define LTYPE_WASTELAND   1
#define LTYPE_RAIDER_CAMP 2
#define LTYPE_GHOUL_RUIN  3
#define LTYPE_MILITARY    4
#define LTYPE_TOWN        5
#define LTYPE_CAVE        6

// ─── Tone codes ───────────────────────────────────────────────────────────
#define TONE_GRIM     0
#define TONE_HOPEFUL  1
#define TONE_HUMOROUS 2
#define TONE_TENSE    3

// ─── File magic numbers ──────────────────────────────────────────────────
#define MAGIC_ENEMIES   0x454E454D
#define MAGIC_ITEMS     0x4954454D
#define MAGIC_LOCATIONS 0x4C4F4341
#define MAGIC_FLAVOR    0x464C4156

// ─── Enemy loot entry (3 bytes) ──────────────────────────────────────────
struct __attribute__((packed)) RPGLootEntry {
    uint16_t name_off;   // string pool offset (0xFFFF = empty)
    uint8_t  weight;     // drop weight 0-255
};

// ─── Enemy entry (30 bytes) ──────────────────────────────────────────────
struct __attribute__((packed)) RPGEnemyEntry {
    uint16_t name_off;
    uint16_t desc_off;
    uint8_t  game_mask;
    uint8_t  faction;
    uint8_t  difficulty;    // 1-4
    uint8_t  defense_rating;
    uint16_t hp_min;
    uint16_t hp_max;
    uint16_t damage_min;
    uint16_t damage_max;
    uint16_t xp_reward;
    uint8_t  loot_count;
    RPGLootEntry loot[3];
    uint8_t  _pad;
};

// ─── Item entry (16 bytes) ───────────────────────────────────────────────
struct __attribute__((packed)) RPGItemEntry {
    uint16_t name_off;
    uint16_t desc_off;
    uint16_t effect_off;   // damage/effect string
    uint8_t  game_mask;
    uint8_t  item_type;    // ITYPE_*
    uint8_t  rarity;       // 1-3
    uint8_t  _pad;
    uint16_t weight_x10;   // weight * 10
    uint16_t value;        // caps
};

// ─── Location entry (18 bytes) ───────────────────────────────────────────
struct __attribute__((packed)) RPGLocationEntry {
    uint16_t name_off;
    uint16_t desc_off;
    uint8_t  game_mask;
    uint8_t  loc_type;     // LTYPE_*
    uint8_t  danger_level; // 1-4
    uint8_t  enemy_count;
    uint16_t enemies[4];   // string pool offsets of enemy names
    uint8_t  region_id;    // REGION_* from FRPGRegions.h (0 = unknown)
    uint8_t  _pad;
};

// ─── Flavor: room description (6 bytes) ──────────────────────────────────
struct __attribute__((packed)) RPGRoomDesc {
    uint16_t text_off;
    uint8_t  loc_type;
    uint8_t  tone;
    uint8_t  game_mask;
    uint8_t  _pad;
};

// ─── Flavor: find/ambient description (4 bytes) ─────────────────────────
struct __attribute__((packed)) RPGFindDesc {
    uint16_t text_off;
    uint8_t  tone;
    uint8_t  _pad;
};

// ─── Flavor: NPC line (6 bytes) ──────────────────────────────────────────
struct __attribute__((packed)) RPGNPCLine {
    uint16_t text_off;
    uint8_t  tone;
    uint8_t  game_mask;
    uint16_t _pad;
};

// ─── File headers ────────────────────────────────────────────────────────

struct __attribute__((packed)) RPGEnemyHeader {
    uint32_t magic;        // MAGIC_ENEMIES
    uint16_t count;
    uint32_t pool_offset;  // byte offset from file start to string pool
    // followed by RPGEnemyEntry[count], then string pool
};

struct __attribute__((packed)) RPGItemHeader {
    uint32_t magic;        // MAGIC_ITEMS
    uint16_t count;
    uint32_t pool_offset;
};

struct __attribute__((packed)) RPGLocationHeader {
    uint32_t magic;        // MAGIC_LOCATIONS
    uint16_t count;
    uint32_t pool_offset;
};

struct __attribute__((packed)) RPGFlavorHeader {
    uint32_t magic;        // MAGIC_FLAVOR
    uint16_t room_count;
    uint16_t find_count;
    uint16_t ambient_count;
    uint16_t npc_count;
    uint32_t pool_offset;
    // followed by RPGRoomDesc[room_count], RPGFindDesc[find_count],
    //            RPGFindDesc[ambient_count], RPGNPCLine[npc_count], then string pool
};

// ─── String pool reader helper ───────────────────────────────────────────
// Read a string from the pool at the given offset.
// Pool format: uint8 length + char[length] (NOT null-terminated in pool).
// Returns pointer and sets outLen. Caller must bounds-check.
inline const char* rpgPoolString(const uint8_t *pool, uint16_t offset, uint8_t &outLen) {
    if (offset == 0xFFFF) { outLen = 0; return nullptr; }
    outLen = pool[offset];
    return (const char *)&pool[offset + 1];
}
