#!/usr/bin/env python3
"""Generate BBSWordleData.h from the existing WORDLE_WORDS in BBSWordle.h.

Scoring: words are ranked by (distinct_letters * sum_of_letter_frequencies).
This prefers common, varied-letter words — good for both Wordle gameplay and
the Vault-Tec hacking game (which needs words with 2-3 positional matches).

Output: module-src/BBSWordleData.h
  - WORDLE_WORD_COUNT = 2000
  - WORDLE_WORDS[][6]  (sorted alphabetically, for binary-search fallback)
  - WORDLE_BLOOM[3072] (8 FNV-1a hashes, ~0.37% false positive rate)
"""

import re, math, os, sys

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
MODULE_DIR  = os.path.join(SCRIPT_DIR, '..', 'module-src')
INPUT_H     = os.path.join(MODULE_DIR, 'BBSWordle.h')
OUTPUT_H    = os.path.join(MODULE_DIR, 'BBSWordleData.h')

TARGET      = 2000
BLOOM_BYTES = 3072   # 24576 bits
BLOOM_K     = 8      # hash functions

# English letter frequency score (e=12 is most common, z=1 least)
FREQ = {
    'e':12,'t':9,'a':8,'o':8,'i':7,'n':7,'s':6,'h':6,'r':6,
    'd':4,'l':4,'c':3,'u':3,'m':2,'w':2,'f':2,'g':2,'y':2,
    'p':2,'b':1,'v':1,'k':1,'j':1,'x':1,'q':1,'z':1
}

def score(w):
    return len(set(w)) * sum(FREQ.get(c, 1) for c in w)

def fnv1a(data: bytes, basis: int) -> int:
    h = basis & 0xFFFFFFFF
    for b in data:
        h = ((h ^ b) * 16777619) & 0xFFFFFFFF
    return h

def bloom_add(bloom: bytearray, word: str):
    d = word.encode('ascii')
    h1 = fnv1a(d, 2166136261)
    h2 = fnv1a(d, 0xdeadbeef)
    m  = len(bloom) * 8
    for i in range(BLOOM_K):
        bit = (h1 + i * h2) % m
        bloom[bit >> 3] |= (1 << (bit & 7))

# ── Parse source ─────────────────────────────────────────────────────────────
# Try reading a plain word-list file first (data/words2k.txt), then fall back
# to extracting quoted words from BBSWordle.h or BBSWordleData.h.
WORDLIST_TXT = os.path.join(SCRIPT_DIR, '..', 'data', 'words2k.txt')

if os.path.exists(WORDLIST_TXT):
    print(f"Reading {WORDLIST_TXT} ...")
    with open(WORDLIST_TXT) as f:
        pool = sorted(set(w.strip().lower() for w in f if len(w.strip()) == 5 and w.strip().isalpha()))
    print(f"  {len(pool)} unique words found")
else:
    # Fall back: scrape quoted 5-letter words from BBSWordle.h or BBSWordleData.h
    candidates = [INPUT_H, OUTPUT_H]
    pool = []
    for path in candidates:
        if not os.path.exists(path):
            continue
        print(f"Reading {path} ...")
        with open(path) as f:
            src = f.read()
        raw = re.findall(r'"([a-z]{5})"', src)
        pool = sorted(set(raw))
        if pool:
            print(f"  {len(pool)} unique words found")
            break
    if not pool:
        print("ERROR: No word source found. Create data/words2k.txt or ensure BBSWordle.h has the full word list.", file=sys.stderr)
        sys.exit(1)

# ── Select top TARGET words ───────────────────────────────────────────────────
ranked  = sorted(pool, key=score, reverse=True)
chosen  = sorted(ranked[:TARGET])          # alphabetical for binary-search use
print(f"  {len(chosen)} words selected (score range "
      f"{score(ranked[TARGET-1])}–{score(ranked[0])})")

# ── Bloom filter ──────────────────────────────────────────────────────────────
bloom = bytearray(BLOOM_BYTES)
for w in chosen:
    bloom_add(bloom, w)

n, m = len(chosen), BLOOM_BYTES * 8
fp = (1 - math.exp(-BLOOM_K * n / m)) ** BLOOM_K
set_bits = sum(bin(b).count('1') for b in bloom)
print(f"  Bloom: {BLOOM_BYTES} B, {BLOOM_K} hashes, "
      f"{100*set_bits/(BLOOM_BYTES*8):.1f}% bits set, "
      f"~{100*fp:.2f}% false-positive rate")

# ── Write header ──────────────────────────────────────────────────────────────
print(f"Writing {OUTPUT_H} ...")
with open(OUTPUT_H, 'w') as f:
    def w(s): f.write(s + '\n')
    w("// Auto-generated by scripts/gen_wordle.py — DO NOT EDIT")
    w(f"// {len(chosen)} common 5-letter words scored by letter frequency")
    w(f"// Bloom: {BLOOM_BYTES} bytes, {BLOOM_K} FNV-1a hashes, ~{100*fp:.2f}% false-positive rate")
    w(f"// Shared by Wordle daily puzzle and Vault-Tec hacking game")
    w("#pragma once")
    w("#include <stdint.h>")
    w("")
    w(f"static const uint32_t WORDLE_WORD_COUNT = {len(chosen)};")
    w("static const char WORDLE_WORDS[][6] = {")
    for i in range(0, len(chosen), 10):
        chunk = chosen[i:i+10]
        line  = "    " + ",".join(f'"{w}"' for w in chunk)
        if i + 10 < len(chosen):
            line += ","
        f.write(line + "\n")
    w("};")
    w("")
    w(f"// Bloom filter: {BLOOM_BYTES} bytes, {BLOOM_K} FNV-1a double-hash functions")
    w(f"// Matches scripts/gen_wordle.py: h(i,x) = (fnv1a(x,2166136261) + i*fnv1a(x,0xdeadbeef)) % {m}")
    w(f"static const uint32_t WORDLE_BLOOM_BYTES = {BLOOM_BYTES};")
    w(f"static const uint32_t WORDLE_BLOOM_K     = {BLOOM_K};")
    w(f"static const uint8_t  WORDLE_BLOOM[{BLOOM_BYTES}] = {{")
    for i in range(0, BLOOM_BYTES, 16):
        chunk = bloom[i:i+16]
        line  = "    " + ",".join(f"0x{b:02x}" for b in chunk)
        if i + 16 < BLOOM_BYTES:
            line += ","
        f.write(line + "\n")
    w("};")

print("Done.")
