#!/usr/bin/env python3
"""
gen_geo_header.py — Convert geo_us.bin into C header chunks for firmware embedding.

Since we can't upload files to nRF52 internal flash from the host, we split
the geo database into chunks small enough to embed in firmware. Each chunk
gets written to external flash on first boot.

The geo database is ~370KB. We split into chunks of ~50KB each (about 8 chunks).
Each chunk is a separate header file that gets compiled in.

Usage:
    python3 scripts/gen_geo_header.py [input] [output_dir]

    Defaults:
        input      → data/geo_us.bin
        output_dir → module-src/geodata/
"""

import os
import sys

CHUNK_SIZE = 50000  # ~50KB per chunk


def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    input_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(script_dir, "..", "data", "geo_us.bin")
    output_dir = sys.argv[2] if len(sys.argv) > 2 else os.path.join(script_dir, "..", "module-src", "geodata")

    if not os.path.exists(input_path):
        print(f"ERROR: {input_path} not found. Run gen_geo_packed.py first.")
        sys.exit(1)

    os.makedirs(output_dir, exist_ok=True)

    with open(input_path, "rb") as f:
        data = f.read()

    total = len(data)
    num_chunks = (total + CHUNK_SIZE - 1) // CHUNK_SIZE

    print(f"Input: {input_path} ({total} bytes)")
    print(f"Splitting into {num_chunks} chunks of ~{CHUNK_SIZE} bytes")

    # Write each chunk as a header
    for i in range(num_chunks):
        start = i * CHUNK_SIZE
        end = min(start + CHUNK_SIZE, total)
        chunk = data[start:end]

        header_path = os.path.join(output_dir, f"geo_chunk_{i}.h")
        with open(header_path, "w") as hf:
            hf.write(f"#pragma once\n")
            hf.write(f"// Auto-generated by gen_geo_header.py — chunk {i}/{num_chunks-1}\n")
            hf.write(f"// Offset: {start}, Size: {len(chunk)}\n\n")
            hf.write(f"static const uint8_t GEO_CHUNK_{i}[] PROGMEM = {{\n")

            for j in range(0, len(chunk), 16):
                row = chunk[j:j+16]
                hf.write("    " + ",".join(f"0x{b:02x}" for b in row) + ",\n")

            hf.write(f"}};\n")
            hf.write(f"static const uint32_t GEO_CHUNK_{i}_SIZE = {len(chunk)};\n")
            hf.write(f"static const uint32_t GEO_CHUNK_{i}_OFFSET = {start};\n")

        print(f"  Chunk {i}: {header_path} ({len(chunk)} bytes)")

    # Write master header
    master_path = os.path.join(output_dir, "geo_chunks.h")
    with open(master_path, "w") as mf:
        mf.write("#pragma once\n")
        mf.write("// Auto-generated by gen_geo_header.py\n")
        mf.write(f"// Total: {total} bytes in {num_chunks} chunks\n\n")
        mf.write("#include <cstdint>\n\n")
        for i in range(num_chunks):
            mf.write(f'#include "geo_chunk_{i}.h"\n')
        mf.write(f"\nstatic const uint32_t GEO_TOTAL_SIZE = {total};\n")
        mf.write(f"static const uint32_t GEO_NUM_CHUNKS = {num_chunks};\n\n")
        mf.write("struct GeoChunkInfo {\n")
        mf.write("    const uint8_t *data;\n")
        mf.write("    uint32_t size;\n")
        mf.write("    uint32_t offset;\n")
        mf.write("};\n\n")
        mf.write("static const GeoChunkInfo GEO_CHUNKS[] = {\n")
        for i in range(num_chunks):
            mf.write(f"    {{ GEO_CHUNK_{i}, GEO_CHUNK_{i}_SIZE, GEO_CHUNK_{i}_OFFSET }},\n")
        mf.write("};\n")

    print(f"\nMaster header: {master_path}")
    print(f"Total: {total} bytes in {num_chunks} chunks")
    print(f"\nTo use: #include \"geodata/geo_chunks.h\" and write chunks to external flash")


if __name__ == "__main__":
    main()
